# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  ChessBot_config = debug

else ifeq ($(config),release)
  ChessBot_config = release

else ifeq ($(config),tests)
  ChessBot_config = tests

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ChessBot

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ChessBot:
ifneq (,$(ChessBot_config))
	@echo "==== Building ChessBot ($(ChessBot_config)) ===="
	@${MAKE} --no-print-directory -C premake/build -f Makefile config=$(ChessBot_config)
endif

clean:
	@${MAKE} --no-print-directory -C premake/build -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  tests"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ChessBot"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"